#!/usr/bin/python3

import sys
import os
from PIL import Image

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: %s [image file]" % (sys.argv[0],))
        sys.exit(1)
    
    im = None

    try:
        im = Image.open(sys.argv[1])
    except FileNotFoundError:
        print("E: File not found")
        sys.exit(1)

    pix = im.load()

    filename = os.path.splitext(sys.argv[1])[0]
    f = open(filename + ".h", "w+")

    f.write("#include <stdint.h>\n\n")
    f.write("static const uint32_t %s_WIDTH = %d;\n" % (filename.upper(), im.size[0]))
    f.write("static const uint32_t %s_HEIGHT = %d;\n" % (filename.upper(), im.size[1]))
    f.write("static const uint8_t %s_DATA[] = {" % (filename.upper()))

    for y in range(0, im.size[1]):
        for x in range(0, im.size[0]):
            try:
                r, g, b = pix[x, y]

                f.write("%s, " % hex(r))
                f.write("%s, " % hex(g))
                f.write("%s, " % hex(b))
            except ValueError:
                r, g, b, a = pix[x, y]

                f.write("%s, " % hex(r))
                f.write("%s, " % hex(g))
                f.write("%s, " % hex(b))
    
    f.write("};\n")
    f.close()